// #region Global Imports
import Head from "next/head"
import { ChangeEvent, useState } from "react"
import { useRouter } from "next/router"
// #endregion Global Imports

// #region Local Imports
import { Input, Space, Button, Tags, Card, MDEditor, QuestionAuthorInfo, Breadcrumbs, Rows, Row } from "@Components"
import { Tab } from "@Components/Molecules/Tabs"
import { Tag } from "@Components/Molecules/Tags"
// #endregion Local Imports

const QuestionCreate = () => {
    const router = useRouter()
    const historyBack = () => {
        if (router.query.prevPath !== undefined) {
            router.back()
        } else {
            router.replace("/community/questions")
        }
    }
    return (
        <>
            <Head>
                <title>Dev Community</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Space padding="16px 24px" bgType="white">
                    <Breadcrumbs
                        BoxProps={{
                            padding: "0",
                        }}
                        breadcrumbList={[
                            {
                                title: "커뮤니티",
                                href: "/community/questions",
                            },
                            {
                                title: "글작성",
                                href: "/community/questions/create",
                            },
                        ]}
                    ></Breadcrumbs>
                </Space>
                <Card.wrap padding={"24px"}>
                    <Card gap={"0"} padding={"0"} direction={"vertical"} bgType={"white"} separator={<div style={{ width: "100%", height: "1px", background: "#0000000F" }}></div>}>
                        <Rows gap="12px">
                            <Input
                                placeholder="제목을 입력해주세요."
                                widthType="wide"
                                value={""}
                                onChange={function (event: ChangeEvent<HTMLInputElement>): void {
                                    throw new Error("Function not implemented.")
                                }}
                            />
                            <Row>
                                <Tags
                                    onAdd={(text) => {
                                        console.log(text)
                                    }}
                                    boxProps={{ padding: "4px" }}
                                    tagList={[
                                        {
                                            title: "Javascript",
                                            type: "deletable",
                                        },
                                    ]}
                                    onClick={function (tag: Tag): void {
                                        throw new Error("Function not implemented.")
                                    }}
                                />
                            </Row>
                        </Rows>
                        <Rows padding="24px">
                            <MDEditor
                                value={""}
                                onChange={function (event: ChangeEvent<HTMLTextAreaElement>): void {
                                    throw new Error("Function not implemented.")
                                }}
                            ></MDEditor>
                            <Row>
                                <QuestionAuthorInfo userName="asd" created={"2021-02-05 13:51"} />
                            </Row>
                            <Row>
                                <Space.Box></Space.Box>
                                <Button>저장</Button>
                                <Button onClick={() => router.back()} type="secondary">
                                    취소
                                </Button>
                            </Row>
                        </Rows>
                    </Card>
                </Card.wrap>
            </div>
        </>
    )
}

export default QuestionCreate
