// #region Global Imports
import Head from "next/head"
import { useRouter } from "next/router"
// #endregion Global Imports

// #region Local Imports
import { Space, Text, Button, Tags, Card, MDEditor, QuestionAuthorInfo, Breadcrumbs, Icon, IconList, Rows, Row } from "@Components"
import { Tag } from "@Components/Molecules/Tags"
import { useUser } from "@Hooks/useUser"
import { GetServerSideProps } from "next"
import { dehydrate, QueryClient, useQuery } from "react-query"
import { HttpQuestionList } from "@Services"
import { useEffect, useState } from "react"
import { Question } from "@Services/Question"
import { useHistoryBack } from "@Hooks/useHistoryBack"
// #endregion Local Imports

const QuestionInfo = () => {
    const router = useRouter()
    const { historyBack } = useHistoryBack("/community/questionList")
    const { user } = useUser()
    const { data } = useQuery(["question", router.query.questionId], () =>
        HttpQuestionList.getQuestion({
            id: Number(router.query.questionId),
        }),
    )
    const question = data || null

    return (
        <>
            <Head>
                <title>Dev Community</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Space padding="16px 24px" bgType="white">
                    <Breadcrumbs
                        BoxProps={{
                            padding: "0",
                        }}
                        breadcrumbList={[
                            {
                                title: "커뮤니티",
                                href: "/community/questionList",
                            },
                            {
                                title: "글제목",
                                href: "/community/questionList/1",
                            },
                        ]}
                    ></Breadcrumbs>
                </Space>
                <Card.wrap padding={"24px"}>
                    <Card gap={"0"} padding={"0"} direction={"vertical"} bgType={"white"} separator={<div style={{ width: "100%", height: "1px", background: "#0000000F" }}></div>}>
                        <Rows gap="12px">
                            <Row>
                                <Space.Box>
                                    <Button onClick={historyBack} type="text" icon={<Icon iconName="xi-arrow-left"></Icon>}></Button>
                                    <Text>{question?.title}</Text>
                                </Space.Box>
                                <Space>
                                    <Button href="/community/questionList/1/modify" type="secondary">
                                        수정
                                    </Button>
                                    <Button danger type="secondary">
                                        삭제
                                    </Button>
                                </Space>
                            </Row>
                            <Row>
                                <Tags
                                    boxProps={{ padding: "4px" }}
                                    tagList={[
                                        {
                                            title: "Javascript",
                                        },
                                    ]}
                                    onClick={function (tag: Tag): void {
                                        throw new Error("Function not implemented.")
                                    }}
                                />
                            </Row>
                        </Rows>
                        <Rows padding="24px">
                            <MDEditor type="preview" value={question?.contents || ""}></MDEditor>
                            <Row>
                                <QuestionAuthorInfo userName={question?.author?.name || ""} created={question?.created} />
                            </Row>
                            <Row>
                                <IconList
                                    iconList={[
                                        {
                                            iconName: "xi-star",
                                            value: "12",
                                        },
                                        {
                                            iconName: "xi-thumbs-up",
                                            value: "41",
                                        },
                                        {
                                            iconName: "xi-message",
                                            value: "13",
                                        },
                                    ]}
                                />
                            </Row>
                        </Rows>
                        <Space direction="vertical" widthType="wide" padding="0">
                            {/* <Rows padding="24px 24px 24px 48px">
                                <Row>
                                    <QuestionAuthorInfo userName="asd" created={"2021-02-05 13:51"} />
                                </Row>
                                <MDEditor
                                    value={`
## MarkdownPreview

> todo: React component preview markdown text.

`}
                                ></MDEditor>
                                <Row>
                                    <Space.Box></Space.Box>
                                    <Button>저장</Button>
                                </Row>
                            </Rows> */}
                            {/* <Rows padding="24px 24px 24px 48px">
                                <Row>
                                    <QuestionAuthorInfo userName="asd" created={"2021-02-05 13:51"} />
                                </Row>
                                <MDEditor
                                    type="preview"
                                    value={`
## MarkdownPreview

> todo: React component preview markdown text.

`}
                                ></MDEditor>
                                <Row>
                                    <IconList
                                        iconList={[
                                            {
                                                iconName: "xi-star",
                                                value: "12",
                                            },
                                            {
                                                iconName: "xi-thumbs-up",
                                                value: "41",
                                            },
                                        ]}
                                    />
                                </Row>
                            </Rows> */}
                        </Space>
                    </Card>
                </Card.wrap>
            </div>
        </>
    )
}
export const getServerSideProps: GetServerSideProps = async ({ query }) => {
    const { questionId } = query
    const queryClient = new QueryClient()
    await queryClient.prefetchQuery(["question", questionId], () =>
        HttpQuestionList.getQuestion({
            id: Number(questionId),
        }),
    )

    return {
        props: {
            dehydratedState: dehydrate(queryClient),
        },
    }
}
export default QuestionInfo
