// #region Global Imports
import Head from "next/head"
import { ChangeEvent, useState } from "react"
import { useRouter } from "next/router"
// #endregion Global Imports

// #region Local Imports
import { Input, Space, Button, Tags, Card, MDEditor, QuestionAuthorInfo, Breadcrumbs, Rows, Row } from "@Components"
import { Tab } from "@Components/Molecules/Tabs"
import { Tag } from "@Components/Molecules/Tags"
import { useUser } from "@Hooks/useUser"
// #endregion Local Imports

const QuestionCreate = () => {
    const router = useRouter()
    const { user } = useUser()
    const [title, setTitle] = useState("")
    const [contents, setContents] = useState("")
    const [tagList, setTagList] = useState<Tag[]>([
        {
            title: "Javascript",
            type: "deletable",
        },
    ])
    const historyBack = () => {
        if (router.query.prevPath !== undefined) {
            router.back()
        } else {
            router.replace("/community/questionList")
        }
    }
    return (
        <>
            <Head>
                <title>Dev Community</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Space padding="16px 24px" bgType="white">
                    <Breadcrumbs
                        BoxProps={{
                            padding: "0",
                        }}
                        breadcrumbList={[
                            {
                                title: "커뮤니티",
                                href: "/community/questionList",
                            },
                            {
                                title: "글작성",
                                href: "/community/questionList/create",
                            },
                        ]}
                    ></Breadcrumbs>
                </Space>
                <Card.wrap padding={"24px"}>
                    <Card gap={"0"} padding={"0"} direction={"vertical"} bgType={"white"} separator={<div style={{ width: "100%", height: "1px", background: "#0000000F" }}></div>}>
                        <Rows gap="12px">
                            <Input
                                placeholder="제목을 입력해주세요."
                                widthType="wide"
                                value={title}
                                onChange={(event) => {
                                    setTitle(event.target.value)
                                }}
                            />
                            <Row>
                                <Tags
                                    onAdd={(text) => {
                                        setTagList([
                                            ...tagList,
                                            {
                                                title: text,
                                                type: "deletable",
                                            },
                                        ])
                                    }}
                                    boxProps={{ padding: "4px" }}
                                    tagList={tagList}
                                    onClick={(tag: Tag) => {
                                        setTagList(tagList.filter((tagObj) => tagObj !== tag))
                                    }}
                                />
                            </Row>
                        </Rows>
                        <Rows padding="24px">
                            <MDEditor
                                value={contents}
                                onChange={(event) => {
                                    setContents(event.target.value)
                                }}
                            ></MDEditor>
                            <Row>
                                <QuestionAuthorInfo userName={user?.name || ""} />
                            </Row>
                            <Row>
                                <Space.Box></Space.Box>
                                <Button>저장</Button>
                                <Button onClick={() => router.back()} type="secondary">
                                    취소
                                </Button>
                            </Row>
                        </Rows>
                    </Card>
                </Card.wrap>
            </div>
        </>
    )
}

export default QuestionCreate
