// #region Global Imports
import Head from "next/head"
import Link from "next/link"
import { ChangeEvent, useState } from "react"
import Image, { ImageLoader } from "next/image"
import classNames from "classnames"
// #endregion Global Imports

// #region Local Imports
import { Tabs, Space, Typography, Button, Search, Tags, Icon } from "@Components"
import { Tab } from "@Components/Molecules/Tabs"
import { Tag } from "@Components/Molecules/Tags"
// #endregion Local Imports

const { Text } = Typography
const myLoader: ImageLoader = ({ src, width, quality }) => {
    return `/public/Images/${src}?w=${width}&q=${quality || 75}`
}
const Home = () => {
    const [activeIdx, setActiveIdx] = useState(0)
    const [tabList, _] = useState([{ title: "Question" }, { title: "Articles", disabled: true }])
    const onClickTab = (tab: Tab, idx: number) => {
        setActiveIdx(idx)
    }
    return (
        <>
            <Head>
                <title>Dev Community</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Button loading>클릭</Button>
                <Button type="secondary">클릭</Button>
                <Button type="dashed">클릭</Button>
                <Button type="link">클릭</Button>
                <Button type="text">클릭</Button>
                <Button disabled>클릭</Button>
                <Button disabled type="secondary">
                    클릭
                </Button>
                <Button disabled type="dashed">
                    클릭
                </Button>
                <Button disabled type="link">
                    클릭
                </Button>
                <Button disabled type="text">
                    클릭
                </Button>
                <Button size="large">클릭</Button>
                <Button size="medium">클릭</Button>
                <Button size="small">클릭</Button>
                <Button danger>클릭</Button>
                <Button danger type="secondary">
                    클릭
                </Button>
                <Button danger type="dashed">
                    클릭
                </Button>
                <Button danger type="link">
                    클릭
                </Button>
                <Button danger type="text">
                    클릭
                </Button>
                <Button disabled danger>
                    클릭
                </Button>
                <Button disabled danger type="secondary">
                    클릭
                </Button>
                <Button disabled danger type="dashed">
                    클릭
                </Button>
                <Button disabled danger type="link">
                    클릭
                </Button>
                <Button disabled danger type="text">
                    클릭
                </Button>
            </div>
        </>
    )
}

export default Home
